### ISSUE TITLE
Some logging seems to be output to the screen

### ISSUE THREAD

**Issue by nicoladj77** [Automattic/vip-wpcom-mu-plugins#8]
There seems to be something which is output to the screen on every request just after the opening body tag

`amp-wp/amp.phpjetpack/jetpack.phpmedia-explorer/media-explorer.phpRewrite-Rules-Inspector/rewrite-rules-inspector.phpwriting-helper/writing-helper.php`

it looks like the list of folders in mu-plugins

http://take.ms/juu3e

**Comment by mjangda** [comment]
Might be because those files are all symlinks. What operating system are you using and what does your WordPress setup look like?

**Comment by nicoladj77** [comment]
@mjangda I'm on Windows 7 64 bit and I'm tring to mirror the [VIP Dev environment](https://vip.wordpress.com/documentation/vip/dev-environment/)

**Comment by steioria** [comment]
Same problem, as well on windows 7 64, this is preventing the correct loading of the mu-plugins. Any fix?

**Comment by joshbetz** [comment]
@nicoladj77 @steioria Can you try the fix in #14? You should be able to switch to that branch with `git pull; git checkout fix/symlinks`.

**Comment by nicoladj77** [comment]
@joshbetz looks like it's working, I can see mu plugins loaded ( and no output )
